#!/usr/bin/bash
#
#   Munin Plugin to graph the number of installed packages and pending updates.
#
#   Copyright © 2015 Ricardo Vieira <ricardo.vieira@tecnico.ulisboa.pt>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

case $1 in
   config)
        cat <<'EOM'
graph_title Installed packages
graph_vlabel Packages
graph_category system
core.label core
core.draw AREA
extra.label extra
extra.draw STACK
community.label community
community.draw STACK
aur.label aur
aur.draw STACK
updates.label updates
updates.draw LINE2
updates.warning 1
EOM
        exit 0;;
esac

printf "core.value "
paclist core | wc -l

printf "extra.value "
paclist extra | wc -l

printf "community.value "
paclist community | wc -l

printf "aur.value "
pacman -Qm | wc -l

printf "updates.value "
checkupdates | wc -l
